MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  #  WEIGHT: '/home/hui/params/pretrained_model/maskrcnn_benchmark/clear_key_model_only_e2e_faster_rcnn_R_50_FPN_1x_tiny200.pth'
  RPN_ONLY: True
  RETINANET_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    NUM_CLASSES: 2
    ANCHOR_SIZES: (8.31, 12.5, 18.55, 30.23, 60.41)# (8, 16, 32, 64, 128)  # (4, 8, 16, 32, 64) will be better
    ASPECT_RATIOS: (0.5, 1., 2)
    ANCHOR_STRIDES: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N: 1000
    BBOX_REG_WEIGHT: 4.0
    LOSS_ALPHA: 0.25 # 0.25
    LOSS_GAMMA: 2.0
    PRIOR_PROB: 0.01
DATASETS:
  TRAIN: ("tiny_set_corner_sw640_sh512_erase_with_uncertain_train_all_coco",)
  TEST: ("tiny_set_corner_sw640_sh512_test_all_coco",)
#  TEST: ("voc_2007_test",)
INPUT:
  USE_SCALE: true
  SCALES: (1,)
DATALOADER:
  SIZE_DIVISIBILITY: 32

SOLVER:
  CHECKPOINT_PERIOD: 9618   # 6 epoch
  TEST_ITER: 9618   # 12 epoch
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (4809, 8015)   # (6 epoch, 10 epoch)  19236, 25648
  MAX_ITER: 9618 # 12 epoch
  IMS_PER_BATCH: 4
  NUM_GPU: 4
TEST:
  IMS_PER_BATCH: 4
  COCO_EVALUATE_STANDARD: 'tiny'  # tiny need change
  MERGE_RESULTS: true
  MERGE_GT_FILE: '../dataset/tiny_set/erase_with_uncertain_dataset/annotations/tiny_set_test_nobox.json'
  IGNORE_UNCERTAIN: true
  USE_IOD_FOR_IGNORE: true
OUTPUT_DIR: ./outputs/tiny_set/retina/50_FPN_1x_4u
TEST_FINAL_ITER: False
NEPTUNE:
  USE_NEPTUNE: True
  PROJECT: beufollow/tiny
  API_TOKEN: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vdWkubmVwdHVuZS5haSIsImFwaV91cmwiOiJodHRwczovL3VpLm5lcHR1bmUuYWkiLCJhcGlfa2V5IjoiY2UyZDg0ZDYtNWRjOS00NTc5LTkxZWMtZTYzZDY5NGQzMDkyIn0=

